Repository allenzhai/Psychify, pull requests merged in 2020-04, with the labels that each got.

#124 Search by Keywords (Name, Alias, Sub-Category, Category) and Sort by Menu
  src/client/pages/SearchResults.js
  src/client/pages/components/ResultsSearchbar.js
  src/client/pages/components/SortMenu.js
  src/client/pages/components/style/SearchResults.css
  src/client/pages/components/style/SortMenu.css
  src/server/__test__/app.test.js
  src/server/api.js
Labels: Search by Keyword, sprint #3

#125 Issue106_107
  src/client/pages/DSM.js
  src/client/pages/components/Login.js
  src/client/pages/components/Navbar.js
  src/client/pages/components/style/Login.css
Labels: sprint #3

#145 Added feature for when you click outside of sort menu, it closes the…
  package.json
  src/client/components/SortMenu.js
  src/client/pages/SearchResults.js
Labels: Search by Keyword, sprint #4

#149 Alphabetized and Styled Index Page with a media break point.
  src/client/pages/DSM.js
  src/client/style/DSM.css
  src/client/style/SearchResults.css
Labels: sprint #4

#152 Issue 138 - Forum Browse Page Front End
  src/client/components/ForumPost.js
  src/client/pages/Forum.js
  src/client/style/Forum.css
  src/client/style/ForumPost.css
  src/client/template/index.html
Labels: sprint #4

#150 Ci integration
  .travis.yml
  package.json
  src/server/__test__/app.test.js
  src/server/database.js
Labels: sprint #4

#154 Cd integration
  .travis.yml
  package.json
  src/client/pages/SearchResults.js
  src/server/database.js
Labels: sprint #4
